"use client";

import React from "react";
import Link from "next/link";
import { ArrowLeft, Shield, Scale, Info, FileText, CheckCircle, Ban } from "lucide-react";
import { motion } from "motion/react";
import ConstellationField from "../components/ConstellationField";

export default function CopyrightPage() {
  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <main className="void-page pt-20 pb-20 px-4 text-white">
      <ConstellationField density="ambient" className="fixed opacity-30" />
      <div className="relative z-10 mx-auto max-w-3xl">
        {/* Back Link */}
        <div className="mb-8">
          <Link
            href="/"
            className="void-ghost inline-flex items-center gap-2"
          >
            <ArrowLeft size={16} />
            Back to Home
          </Link>
        </div>

        {/* Title / Hero */}
        <header className="mb-12 text-center">
          <div className="void-kicker mb-5 inline-flex items-center gap-2">
            <Scale size={16} />
            IP & Copyright Policy Draft
          </div>
          <h1 className="void-heading mb-4">
            Intellectual Property Policy
          </h1>
          <p className="text-[--color-ash-gray] text-sm">Last updated: {currentDate}</p>
        </header>

        {/* Disclaimer Callout */}
        <div className="mb-8 border-t border-b border-yellow-500/30 py-4 text-sm text-yellow-200/90 leading-relaxed">
          <strong className="text-[--color-saffron-spark]">Important Note:</strong> This is a working draft based on a review of the EchoMind codebase. It does not constitute legal advice. If you want DMCA safe-harbor protection (for US-based users or hosting), please consult with a lawyer to formally register a DMCA agent with the US Copyright Office.
        </div>

        {/* Content Card */}
        <motion.div
          className="space-y-8 border-t void-hairline pt-8"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
        >
          {/* 1. Our intellectual property */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-violet-300 flex items-center gap-2">
              <Shield size={22} className="text-violet-400 shrink-0" />
              1. Our intellectual property
            </h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              EchoMind, its name, branding, logos, and underlying software (including the frontend, server components, and database configurations) are the exclusive property of EchoMind. You may not copy, modify, reverse-engineer, redistribute, or use any part of our intellectual property without our express written permission.
            </p>
          </section>

          <hr className="border-white/10" />

          {/* 2. AI-generated content */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-violet-300 flex items-center gap-2">
              <Info size={22} className="text-teal-400 shrink-0" />
              2. AI-generated content
            </h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              EchoMind&apos;s companion responses are generated by AI models. While we take reasonable steps to avoid doing so, AI-generated content can occasionally resemble existing third-party content unintentionally. We do not knowingly reproduce copyrighted material, and we do not claim ownership over incidental resemblances that may occur in AI output.
            </p>
          </section>

          <hr className="border-white/10" />

          {/* 3. Reporting a claim of infringement */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-violet-300 flex items-center gap-2">
              <FileText size={22} className="text-violet-400 shrink-0" />
              3. Reporting a claim of infringement
            </h2>
            <p className="text-gray-300 text-sm leading-relaxed font-light">
              If you believe content associated with EchoMind infringes your copyright or other intellectual property rights, please send a written notice to our designated contact below containing:
            </p>

            <ol className="list-decimal pl-6 space-y-2 text-gray-300 text-xs leading-relaxed">
              <li>Your physical or electronic signature (or that of a person authorized to act on your behalf).</li>
              <li>Identification of the copyrighted work (or other IP) you claim is infringed.</li>
              <li>Identification of the material you claim is infringing, and information reasonably sufficient for us to locate it.</li>
              <li>Your contact information (address, phone number, and email).</li>
              <li>A statement that you have a good-faith belief that the use is not authorized by the copyright/IP owner, its agent, or the law.</li>
              <li>A statement, made under penalty of perjury, that the information in the notice is accurate and that you are the owner (or authorized to act on behalf of the owner) of the exclusive right allegedly infringed.</li>
            </ol>

            <div className="rounded-xl border border-white/5 bg-white/[0.01] p-4 text-sm text-gray-300 space-y-1">
              <p><strong className="text-white">Designated IP Agent:</strong> IP Redressal Agent (EchoMind Support)</p>
              <p><strong className="text-white">Email Address:</strong> <a href="mailto:privacy@echomind.ai" className="text-teal-400 hover:underline">privacy@echomind.ai</a></p>
              <p><strong className="text-white">Contact Mailing Address:</strong> support@echomind.ai (Grievance Support Desk)</p>
            </div>
          </section>

          <hr className="border-white/10" />

          {/* 4. Counter-notification */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-violet-300 flex items-center gap-2">
              <CheckCircle size={22} className="text-teal-400 shrink-0" />
              4. Counter-notification
            </h2>
            <p className="text-gray-300 text-sm leading-relaxed font-light">
              If you believe content was removed or disabled by mistake or misidentification, you may submit a counter-notice containing:
            </p>
            <ol className="list-decimal pl-6 space-y-2 text-gray-300 text-xs leading-relaxed">
              <li>Your physical or electronic signature.</li>
              <li>Identification of the material removed and its location before removal.</li>
              <li>A statement under penalty of perjury that you have a good-faith belief that the material was removed as a result of mistake or misidentification.</li>
              <li>Your name, address, and phone number, and a statement consenting to the jurisdiction of the courts in your district (or, if outside the US, the relevant jurisdiction) and that you will accept service of process from the complaining party.</li>
            </ol>
          </section>

          <hr className="border-white/10" />

          {/* 5. Repeat infringers */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-violet-300 flex items-center gap-2">
              <Ban className="text-violet-400 shrink-0" size={22} />
              5. Repeat infringers
            </h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              We may terminate accounts of users determined to be repeat infringers, at our sole discretion, in order to protect rights holders.
            </p>
          </section>

          <hr className="border-white/10" />

          {/* 6. Trademark */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-violet-300 flex items-center gap-2">
              <Scale size={22} className="text-teal-400 shrink-0" />
              6. Trademark
            </h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              &quot;EchoMind&quot; and associated logos are trademarks of EchoMind. Unauthorized use of our name or branding in a way that may confuse users is strictly prohibited.
            </p>
          </section>

          <hr className="border-white/10" />

          {/* 7. Contact */}
          <section className="space-y-4 text-center">
            <h2 className="text-2xl font-semibold text-violet-300">7. Contact us</h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              For any IP and copyright inquiries, please contact us at:{" "}
              <a
                href="mailto:support@echomind.ai"
                className="text-teal-400 hover:underline hover:text-teal-300 transition-colors"
              >
                support@echomind.ai
              </a>
            </p>
          </section>
        </motion.div>
      </div>
    </main>
  );
}

